name: CI & Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-php@v4
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, sqlite, exif, pcntl
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --optimize-autoloader
      - name: Prepare .env & Key
        run: |
          cp .env.example .env
          php artisan key:generate
      - name: Setup SQLite
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Run Migrations
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan migrate --force
      - name: Run Tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test --verbose

  deploy:
    name: Deploy to Dev Server
    needs: tests
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v4
      # aquí pon tus pasos de deploy, p.ej. rsync, scp, FTP, o un Action de tu cloud.
      - name: Deploy to Dev
        run: |
          echo "Desplegando a DEV..."
          # scp -r ./ user@dev.server:/ruta/app


